import { pgTable, text, timestamp, integer, jsonb, boolean, index, unique } from "drizzle-orm/pg-core";
import { projectsTable } from "./projects";
import { usersTable } from "./users";

export type DailyReportData = {
  subcontractorsOnSite: {
    id: string;
    workerName: string;
    checkedInAt: string;
    photoUrl: string | null;
  }[];
  documentActivity: {
    uploaded: { documentId: string; name: string; type: string; version: number; uploaderName: string; at: string }[];
    amended: { documentId: string; name: string; type: string; version: number; uploaderName: string; at: string }[];
    viewed: { documentId: string; documentName: string; userName: string; at: string }[];
    signedOff: {
      documentId: string;
      documentName: string;
      documentVersion: number;
      userName: string;
      userRole: string;
      signedOffWithPin: boolean;
      at: string;
    }[];
  };
  sitePhotos: {
    id: string;
    referenceNumber: string;
    category: string;
    description: string | null;
    zone: string | null;
    uploaderName: string;
    photoUrl: string | null;
    takenAt: string;
  }[];
  siteManagerNotes: {
    id: string;
    authorName: string;
    body: string;
    source: string;
    at: string;
  }[];
};

// F5 — the manager/worker-authored structured "site diary". Separate from the
// immutable auto `data` snapshot: this is editable at any time (incl. before the
// 18:00 job runs) and every field is optional. Voice-to-text on the free-text
// fields fills the same strings client-side — no per-field source tracking needed.
export type ManagerReport = {
  weather?: string;
  labourOnSite?: string;
  plantEquipment?: string;
  workCompleted?: string;
  delaysIssues?: string;
  deliveries?: string;
  hsNotes?: string;
};

// One immutable end-of-day snapshot per project per day. The collated activity is
// frozen into `data` (jsonb) at generation time so the report stays accurate even
// if underlying records change later.
export const dailyReportsTable = pgTable("daily_reports", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull().references(() => projectsTable.id, { onDelete: "cascade" }),
  // YYYY-MM-DD in Europe/London (the day the report covers).
  reportDate: text("report_date").notNull(),
  generatedAt: timestamp("generated_at").notNull().defaultNow(),
  checkinCount: integer("checkin_count").notNull().default(0),
  documentEventCount: integer("document_event_count").notNull().default(0),
  photoCount: integer("photo_count").notNull().default(0),
  data: jsonb("data").$type<DailyReportData>().notNull(),
  // F5 — editable structured site diary (nullable: a report can exist as an auto
  // snapshot with no manager narrative, or be authored early before any auto data).
  managerReport: jsonb("manager_report").$type<ManagerReport>(),
  authoredBy: text("authored_by").references(() => usersTable.id),
  authoredAt: timestamp("authored_at"),
  // False until the 18:00 job has populated the auto `data`/counts. A report row
  // can be created early by an author (narrative only) with this still false; the
  // generator fills the auto data exactly once (false→true) and notifies then.
  autoGenerated: boolean("auto_generated").notNull().default(false),
  // Draft/submit lifecycle (Feature: portal save-vs-submit). NULL = draft — the
  // PM's report view doesn't show managerReport content until submitted. Once
  // set, direct edits to managerReport are blocked in favor of the append-only
  // notes table; this is separate from (and checked alongside) the existing
  // date-based isReportLocked() window.
  submittedAt: timestamp("submitted_at"),
  submittedBy: text("submitted_by").references(() => usersTable.id),
}, (t) => [
  unique("daily_reports_project_date_uq").on(t.projectId, t.reportDate),
  index("daily_reports_project_idx").on(t.projectId),
]);

export type DailyReport = typeof dailyReportsTable.$inferSelect;
